# This is a basic workflow to help you get started with Actions

name: Deploy to Production

# Controls when the action will run.
on:
  workflow_run:
    workflows: [ "Switcharoohelper Unit Tests" ]
    branches: [ master ]
    types:
      - completed

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  on-success:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            whoami
            systemctl --user stop switcharoo_main.service
            cd ~/switcharoo
            git pull origin master
            cp ~/switcharoo/config/services/* ~/.config/systemd/user
            python3 -m poetry install --sync
            echo "${{ secrets.CONFIG }}" > ~/switcharoo/credentials.ini
            crontab ~/switcharoo/config/cron.jobs
            systemctl --user daemon-reload
            systemctl --user start switcharoo_main.service
